services:
  evolution:
    image: atendai/evolution-api:v1.5.7
    container_name: glamnail_evolution
    environment:
      SERVER_TYPE: http
      SERVER_PORT: 8080
      AUTHENTICATION_API_KEY: 429683C4C977415CAAFCCE10F7D57E11
      DATABASE_ENABLED: false
    ports:
      - "8080:8080"
    volumes:
      - evolution_data:/usr/src/app/storage
    restart: unless-stopped
volumes:
  evolution_data:
